### ISSUE TITLE
Time varying

### ISSUE THREAD

**Issue by PARODBE** [autonlab/DeepSurvivalMachines#58]
Hi!

Thank you for this work. Are there any possibility of use this library for survival analysis with time varying using deep learning approaches???

Thanks
Pablo

**Comment by chiragnagpal** [comment]
The recurrent Deep survival machines is designed to work with Time-varying covariates. Please check 
https://autonlab.github.io/DeepSurvivalMachines/#deep-recurrent-survival-machines
https://github.com/autonlab/DeepSurvivalMachines/blob/master/examples/RDSM%20on%20PBC%20Dataset.ipynb
